on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        app: [docker, podman]

    env:
      IMAGE: ghcr.io/${{ github.repository }}-${{ matrix.app }}

    steps:
      - run: |
          sudo apt-get -y update
          sudo apt-get -y install podman

      - run: |
          echo 'FROM alpine
          LABEL org.opencontainers.image.source=https://github.com/${{ github.repository }}' > Dockerfile

      - run: ${{ matrix.app }} build . -t ${{ env.IMAGE }}

      - run: ${{ matrix.app }} login ghcr.io -u token -p ${{ secrets.WRITE_PACKAGES_TOKEN }}

      - run: ${{ matrix.app }} push ${{ env.IMAGE }}
