on:
  push:

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          sudo apt-get -y update
          sudo apt-get -y install podman

      - run: podman build . -t ${{ env.IMAGE }}

      - run: podman login ghcr.io -u token -p ${{ secrets.WRITE_PACKAGES_TOKEN }}

      - run: podman push ${{ env.IMAGE }}
